// Baseline copy is also used by the one-time Sanity migration export.
export const defaultSettings = {
 companyName: 'Intelligence Layer', contactEmail: 'connect@intelligencelayer.com.au', contactCta: 'Start a conversation',
 locationDescription: 'Brisbane, Australia', defaultSeoTitle: 'AI Automation & XR Studio Brisbane | Intelligence Layer',
 defaultMetaDescription: 'Intelligence Layer builds AI automation, custom VR, AR and mixed reality experiences for organisations across Brisbane and Australia.', socialLinks: [],
};
export const defaultHomepage = {
 heroEyebrow: 'AI & immersive technology studio', heroHeading: 'AI automation and immersive experiences built for the real world.',
 heroIntroduction: 'Intelligence Layer designs AI-powered systems and custom VR, AR and mixed reality experiences for organisations across Brisbane and Australia.',
 primaryCtaLabel: 'Start a project', primaryCtaDestination: '#contact', secondaryCtaLabel: 'See our work',
 workIntroduction: 'Immersive applications, conversational AI and spatial concepts. A selection of what we build.',
 aiHeading: 'Put AI inside the work your team already does.',
 aiIntroduction: 'We design AI systems that connect your tools, information and processes so repetitive work happens automatically and people can focus on decisions that matter.',
 xrHeading: 'Create experiences people can step inside.',
 xrIntroduction: 'We design and build immersive experiences across VR, AR, MR and the web, from early prototypes and digital twins to training, visualisation and production-ready interactive experiences.',
 buildIntroduction: 'Start with the problem you need to solve. We shape the technology around it.',
 processIntroduction: 'Emerging technology matters when it solves a real problem. Our delivery model keeps the work grounded from the first conversation.',
 productsIntroduction: "We don't only build technology for clients. We build our own. These ventures put our product development experience into practice.",
 finalCtaHeading: "Tell us what you're trying to build.", finalCtaCopy: "Whether you're exploring AI automation, a VR experience, mixed reality, a digital twin or something that does not quite fit a category, we can help turn the idea into a practical next step.",
 aiCapabilities: ['AI agents and workflow automation', 'Document and data processing', 'Internal knowledge assistants', 'Customer support automation', 'Reporting and analysis', 'AI-enabled SaaS products', 'Integrations between existing systems'],
 xrCategories: [ ['Virtual Reality', 'Training, simulation, product experiences, games and immersive applications, including Meta Quest development.'], ['Mixed Reality', 'Experiences that combine digital content with the physical environment.'], ['Augmented Reality', 'Interactive information and digital content placed into the real world.'], ['WebXR & Digital Twins', 'Interactive 3D and spatial experiences accessible across browsers, desktop, mobile and headsets.'] ].map(([title, description]) => ({title, description})),
 outcomes: [ ['Automate a business process', 'Replace repetitive manual workflows with AI-driven systems.'], ['Build an AI assistant', 'Give teams an intelligent interface to organisational knowledge, tools and systems.'], ['Create immersive training', 'Let people practise procedures and environments safely through VR or MR.'], ['Visualise something complex', 'Turn facilities, infrastructure, environments or data into interactive spatial experiences.'], ['Create a product experience', 'Build something customers can explore and interact with instead of simply reading about.'], ['Prototype an emerging technology idea', 'Validate an AI, AR, VR or MR concept before committing to a full production build.'] ].map(([title, description]) => ({title, description})),
 ventures: [ { title: 'Cybersecurity Check', description: 'Understand your external security exposure before it becomes a problem.' }, { title: 'Cleaning QA', description: 'Make quality assurance visible, accountable and easier to manage.' }, { title: 'Inlyr', description: 'Turn customer feedback into clear, prioritised actions.' } ],
 seo: {},
};
export const defaultVrService = {
 id: 'service-vr-development', title: 'Virtual Reality Development', slug: 'vr-development', category: 'xr' as const,
 headline: 'Custom Virtual Reality Development', shortDescription: 'Custom VR experiences, Meta Quest applications, immersive training, simulations and spatial software.',
 introduction: 'Intelligence Layer designs and develops custom virtual reality experiences for organisations across Brisbane and Australia. From Meta Quest applications and immersive training to interactive simulations, visualisation and branded VR experiences, we take projects from early concept through to deployment.',
 overviewHeading: 'What does a VR development company do?', overviewCopy: 'We shape the experience, design interactions, build the application and test it for the intended environment. Discovery connects your objectives with a practical plan for content, hardware and deployment.',
 useCases: [ ['VR training', 'Practise procedures and decision-making in a controlled virtual environment.'], ['Interactive simulations', 'Explore scenarios and systems through hands-on interaction.'], ['Product visualisation', 'Experience scale, form and function in three dimensions.'], ['Immersive storytelling', 'Bring places and narratives into an interactive environment.'], ['Trade show experiences', 'Give visitors a focused experience of your product or idea.'], ['Digital twins', 'Explore a spatial representation of a facility or environment.'], ['Education', 'Make concepts tangible through guided exploration.'], ['Games and entertainment', 'Create VR-native play and spatial interaction.'], ['Location-based VR', 'Scope experiences around a physical venue and its operating requirements.'], ['Prototype experiences', 'Test the core interaction before investing in a full application.'] ].map(([title, description]) => ({title, description})),
 technologies: ['Meta Quest', 'PC VR', 'Hand Tracking', 'Mixed Reality', 'Unity', 'WebXR'],
 capabilities: [
 {title: 'Meta Quest & Unity', description: 'For Meta Quest applications, we evaluate standalone headset requirements, including Quest 3 or Quest 3S where appropriate, and test against the agreed devices.'},
 {title: 'PC VR & SteamVR', description: 'PC VR may suit experiences with demanding visual or computing requirements. SteamVR compatibility and specific hardware support are scoped and validated for each project.'},
 {title: 'WebXR', description: 'Browser-based spatial experiences can reach people on desktop, mobile and compatible headsets. Browser and device capabilities determine the available interactions.'},
 {title: 'Natural interaction', description: 'Hand tracking, controller-based interaction and mixed reality each suit different tasks. We prototype the appropriate approach and confirm support on the target hardware.'},
 ],
 faqs: [
 ['How much does VR development cost in Australia?', 'VR development cost depends on interaction complexity, the quantity and quality of 3D content, the number of environments and the target hardware. Integrations, multiplayer or networking, backend systems, testing and deployment also affect the scope. A focused prototype is considerably less expensive than a production-grade training platform or a large multi-environment experience. We define the scope with you before estimating the work.'],
 ['How long does it take to build a VR experience?', 'A focused VR prototype may take weeks, while larger production applications can take multiple months. Content creation, interaction design, integrations and testing all influence the timeline. Discovery establishes a delivery plan around the actual scope rather than a fixed promise.'],
 ['Can you build VR applications for Meta Quest?', 'Yes. We establish the target headset, interaction requirements and deployment approach during discovery.'],
 ['Can VR integrate with existing systems?', 'Yes. A VR application can connect to existing systems through APIs and backend services, for example to retrieve content or record training activity. We assess authentication, data handling, connectivity and the available interfaces before defining the integration.'],
 ['Do we own the application?', 'Application ownership, source code access and licensing are determined in the project agreement. We clarify these arrangements before work begins, including any third-party assets or platform dependencies.'],
 ['Do you provide hardware?', 'Hardware selection and procurement requirements are discussed during discovery. We can help identify appropriate headsets and plan deployment requirements; hardware supply and purchasing responsibilities must be agreed for the project.'],
 ['What is the difference between VR, AR and mixed reality?', 'Virtual reality places people inside a digital environment. Augmented reality places digital information into a view of the real world. Mixed reality lets digital content interact with the physical environment. The appropriate approach depends on the task, audience and setting.'],
].map(([question, answer]) => ({question, answer})),
 productionCapabilities: ['XR and Unity development', 'Interaction design', 'Technical architecture', '3D environments and assets', 'Character production', 'Animation', 'VFX', 'Motion capture', 'UI and spatial interface design', 'Audio and media production', 'Backend and system integrations'],
 deliveryHeading: 'Built by the right team for the experience.',
 deliveryIntroduction: 'Immersive projects often combine software development, interaction design and specialist content production. We build the team around the experience, bringing together the technical and creative skills required to take a project from concept through to deployment.',
 deliveryApproach: 'From focused prototypes to multidisciplinary immersive projects, we build the team and delivery approach around what the experience actually requires.',
 workIntroduction: 'Immersive experiences built around practical interaction, training and spatial visualisation.',
 seo: {metaTitle: 'VR Development Brisbane & Australia | Intelligence Layer', metaDescription: 'Intelligence Layer builds custom VR experiences, Meta Quest applications, immersive training and simulations for organisations across Brisbane and Australia.'},
};
