import { defineArrayMember, defineField, defineType } from 'sanity';
import {defaultMarketingCopy,marketingKeys,marketingGroup,marketingTitle} from '../src/data/marketing';
const requiredText = (name: string, title: string, description?: string) => defineField({name, title, description, type: 'string', validation: r => r.required()});
const paragraph = (name: string, title: string, required = false, description?: string) => defineField({name, title, description, type: 'text', rows: 3, validation: r => required ? r.required() : r});
const stringList = (name: string, title: string, description?: string) => defineField({name, title, description, type: 'array', of: [defineArrayMember({type: 'string'})], validation: r => r.unique()});
const contentItems = (name: string, title: string) => defineField({name, title, type: 'array', of: [defineArrayMember({type: 'contentItem'})]});
const refs = (name: string, title: string, types: string[]) => defineField({name, title, type: 'array', of: [defineArrayMember({type: 'reference', to: types.map(type => ({type}))})], validation: r => r.unique()});
const slugField = defineField({name: 'slug', title: 'URL slug', type: 'slug', description: 'Generate a unique lowercase URL. Changing a live slug requires a developer-managed redirect.', options: {source: 'title', maxLength: 80}, validation: r => r.required().custom(v => !v?.current || /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v.current) ? true : 'Use lowercase words separated by single hyphens.')});
const seoField = defineField({name: 'seo', title: 'Search and social appearance', type: 'seo'});
const bodyField = defineField({name: 'body', title: 'Main content', type: 'portableContent', description: 'Use H2 for main sections and H3/H4 within them. The page title is always the H1.'});
const singletonRule = (id: string) => defineType({name: id, title: id === 'homepage' ? 'Homepage' : 'Site settings', type: 'document', fields: [], validation: rule => rule.custom(v => v?._id?.replace(/^drafts\./,'') === id ? true : 'Edit the existing singleton from the Content menu.')});
export const schemaTypes = [
 defineType({name:'marketingCopy',title:'Page headings & enquiry copy',type:'document',initialValue:defaultMarketingCopy,groups:[{name:'homepage',title:'Homepage sections',default:true},{name:'pages',title:'Service, industry & About pages'},{name:'enquiry',title:'Project enquiry'},{name:'callsToAction',title:'Process & calls to action'}],fields:marketingKeys.map(key=>defineField({name:key,title:marketingTitle(key),group:marketingGroup(key),type:/Introduction|Copy|NextSteps|Guidance|Responsibility|Heading/.test(key) ? 'text' : 'string',description:`Leave blank to use the default: ${defaultMarketingCopy[key]}`,validation:r=>r.max(/Introduction|Copy|NextSteps|Guidance|Responsibility|Heading/.test(key) ? 1000 : 180)})),validation:r=>r.custom(v=>v?._id?.replace(/^drafts\./,'') === 'marketingCopy' ? true : 'Edit the existing Page headings & enquiry copy document from the Content menu.'),preview:{prepare:()=>({title:'Page headings & enquiry copy'})}}),
 defineType({name:'commercialContent',title:'Industries, process & About',type:'document',validation:r=>r.custom(v=>v?._id?.replace(/^drafts\./,'') === 'commercialContent' ? true : 'Use the existing document from the Content menu.'),fields:[
  defineField({name:'industries',title:'Industries (display order)',type:'array',of:[defineArrayMember({name:'industry',type:'object',fields:[requiredText('title','Sector'),paragraph('description','Problem and example applications',true,'Describe potential use cases. Do not imply an existing client engagement.'),defineField({name:'services',title:'Relevant services',type:'array',of:[defineArrayMember({type:'string',options:{list:[{title:'AI Automation',value:'ai-automation'},{title:'Enterprise AI Agents',value:'enterprise-ai-agents'},{title:'Immersive Experiences',value:'immersive-experiences'},{title:'Digital Twins',value:'digital-twins'}]}})],validation:r=>r.required().min(1).unique()})]})],validation:r=>r.required().min(1)}),
  {...contentItems('processSteps','Delivery process'),validation:r=>r.required().length(6)},
  requiredText('aboutTitle','About heading'),paragraph('aboutIntroduction','About introduction',true),paragraph('aboutDelivery','Delivery responsibility',true),paragraph('aboutEvidence','Work and experience context',true),
  defineField({name:'team',title:'Team (display order)',type:'array',of:[defineArrayMember({name:'teamMember',type:'object',fields:[requiredText('name','Name'),defineField({name:'role',title:'Role (only when approved)',type:'string'}),paragraph('biography','Biography',false,'Use approved facts; do not invent credentials or years of experience.'),defineField({name:'image',title:'Portrait',type:'editorialImage'}),defineField({name:'approvedForPublication',title:'Approved for publication',type:'boolean',initialValue:false})]})],description:'Only approved entries appear publicly. An empty list removes all team entries.'}),
 ],preview:{prepare:()=>({title:'Industries, process & About'})}}),
 defineType({name: 'editorialImage', title: 'Editorial image', type: 'image', options: {hotspot: true}, fields: [requiredText('alt', 'Alternative text', 'Describe the meaningful image content for readers who cannot see it. Do not use keyword lists.'), defineField({name: 'caption', title: 'Caption', type: 'string'})], validation: r => r.custom(value => !value || value.asset ? true : 'Upload or select an image.')}),
 defineType({name: 'seo', title: 'SEO', type: 'object', fields: [
  defineField({name: 'metaTitle', title: 'Custom page title (optional)', type: 'string', description: 'Leave blank to use the page title. Avoid repeating locations or keywords.', validation: r => [r.custom(v => v === undefined || v === null || v.trim() ? true : 'Enter a title or clear this field.'), r.max(65).warning('Long titles may be truncated in search results.')]}),
  defineField({name: 'metaDescription', title: 'Custom description (optional)', type: 'text', rows: 2, description: 'Leave blank to use the page introduction or excerpt.', validation: r => r.max(170).warning('Long descriptions may be truncated.')}),
  defineField({name: 'canonicalUrl', title: 'Advanced: canonical URL override', type: 'url', description: 'Normally leave blank. Only change after discussing duplicate/canonical content with a developer.', validation: r => r.uri({scheme: ['https']})}),
  defineField({name: 'ogTitle', title: 'Social title (optional)', type: 'string'}),
  paragraph('ogDescription', 'Social description (optional)'),
  defineField({name: 'ogImage', title: 'Social sharing image', type: 'editorialImage'}),
  defineField({name: 'noIndex', title: 'EXCLUDE this page from search engines', type: 'boolean', initialValue: false, description: 'Leave OFF for normal public content. Turning this on adds noindex and removes the page from the sitemap.'}),
 ]}),
 defineType({name: 'faq', title: 'Buyer question', type: 'object', fields: [requiredText('question', 'Question'), paragraph('answer', 'Answer', true, 'Give a direct, useful answer. Do not invent pricing, guarantees or contract terms.')], preview: {select: {title: 'question', subtitle: 'answer'}}}),
 defineType({name: 'contentItem', title: 'Capability or use case', type: 'object', fields: [requiredText('title', 'Heading'), paragraph('description', 'Description', true)], preview: {select: {title: 'title', subtitle: 'description'}}}),
 defineType({name: 'videoEmbed', title: 'Video', type: 'object', fields: [
  defineField({name: 'provider', title: 'Delivery platform', type: 'string', options: {list: [{title: 'YouTube', value: 'youtube'}, {title: 'Vimeo', value: 'vimeo'}, {title: 'Hosted MP4 / WebM', value: 'file'}]}, validation: r => r.required()}),
  defineField({name: 'url', title: 'Video URL', type: 'url', description: 'Use a YouTube watch URL, public Vimeo URL or a direct hosted .mp4/.webm URL. Do not upload large videos to this repository.', validation: r => r.required().uri({scheme: ['https']}).custom((v, context) => {
   if (!v) return true; const provider = context.parent && (context.parent as {provider?: string}).provider;
   try {const u = new URL(v); if (provider === 'youtube' && ['youtube.com','www.youtube.com','youtu.be'].includes(u.hostname)) return true; if (provider === 'vimeo' && ['vimeo.com','www.vimeo.com'].includes(u.hostname) && /^\/\d+$/.test(u.pathname)) return true; if (provider === 'file' && /\.(mp4|webm)$/i.test(u.pathname)) return true;} catch { /* Handled by URL validation. */ }
   return 'Use a URL matching the selected delivery platform.';
  })}), requiredText('title', 'Accessible video title'), defineField({name: 'caption', type: 'string', title: 'Caption'}),
 ]}),
 defineType({name: 'callout', title: 'Callout', type: 'object', fields: [defineField({name: 'title', type: 'string', title: 'Heading (optional)'}), paragraph('text', 'Text', true)]}),
 defineType({name: 'portableContent', title: 'Editorial content', type: 'array', of: [
  defineArrayMember({type: 'block', styles: [{title: 'Paragraph', value: 'normal'}, {title: 'Heading 2', value: 'h2'}, {title: 'Heading 3', value: 'h3'}, {title: 'Heading 4', value: 'h4'}, {title: 'Quote', value: 'blockquote'}], lists: [{title: 'Bullet list', value: 'bullet'}, {title: 'Numbered list', value: 'number'}], marks: {decorators: [{title: 'Strong', value: 'strong'}, {title: 'Emphasis', value: 'em'}], annotations: [
   defineArrayMember({name: 'link', title: 'External link', type: 'object', fields: [defineField({name: 'href', title: 'URL', type: 'url', validation: r => r.required().uri({scheme: ['https', 'http']})})]}),
   defineArrayMember({name: 'internalLink', title: 'Link to site content', type: 'object', fields: [defineField({name: 'target', title: 'Page', type: 'reference', to: [{type: 'service'}, {type: 'project'}, {type: 'insight'}], validation: r => r.required()})]}),
  ]}}), defineArrayMember({type: 'editorialImage'}), defineArrayMember({type: 'videoEmbed'}), defineArrayMember({type: 'callout'}),
 ]}),
 defineType({...singletonRule('siteSettings'), fields: [requiredText('companyName', 'Company name'), defineField({name: 'contactEmail', title: 'Contact email', type: 'email', validation: r => r.required()}), requiredText('contactCta', 'General contact CTA'), requiredText('locationDescription', 'Location description', 'Use a natural Australian location description, such as Brisbane, Australia.'), requiredText('defaultSeoTitle', 'Default SEO title'), paragraph('defaultMetaDescription', 'Default SEO description', true), defineField({name: 'defaultOgImage', title: 'Default social image', type: 'editorialImage'}), defineField({name: 'socialLinks', title: 'Social links', type: 'array', of: [defineArrayMember({type: 'object', name: 'socialLink', fields: [requiredText('label', 'Link label'), defineField({name: 'url', title: 'URL', type: 'url', validation: r => r.required().uri({scheme: ['https']})})]})]})], preview: {prepare: () => ({title: 'Site settings'})}}),
 defineType({...singletonRule('homepage'), fields: [
  requiredText('heroEyebrow', 'Hero eyebrow'), requiredText('heroHeading', 'Hero heading', 'This is the homepage H1. Clearly explain AI automation and immersive technology in natural language.'), paragraph('heroIntroduction', 'Hero introduction', true), requiredText('primaryCtaLabel', 'Primary CTA label'), defineField({name: 'primaryCtaDestination', title: 'Primary CTA destination', type: 'string', description: 'Use a site path, #contact, or a full HTTPS URL.', validation: r => r.required().custom(v => !v || /^(#[a-zA-Z][\w-]*|\/(?!\/)[a-zA-Z0-9/_#?=&%.-]*|https:\/\/[^\s]+)$/.test(v) ? true : 'Use a site path, anchor or HTTPS URL.')}), requiredText('secondaryCtaLabel', 'See our work CTA label'), refs('featuredProjects', 'Selected projects (display order)', ['project']), paragraph('workIntroduction', 'Selected work introduction'), requiredText('aiHeading', 'AI section heading', 'Keep practical AI automation clearly identifiable.'), paragraph('aiIntroduction', 'AI introduction', true), stringList('aiCapabilities', 'AI capabilities'), requiredText('xrHeading', 'XR section heading', 'Explain the purpose of immersive experiences without keyword lists.'), paragraph('xrIntroduction', 'XR introduction', true), contentItems('xrCategories', 'XR categories'), paragraph('buildIntroduction', 'What we can build introduction'), contentItems('outcomes', 'What we can build'), paragraph('processIntroduction', 'Process introduction'), paragraph('productsIntroduction', 'Products & Ventures introduction'), defineField({name: 'ventures', title: 'Product descriptions', type: 'array', of: [defineArrayMember({type: 'contentItem'})], description: 'Three items in this order: Cybersecurity Check, Cleaning QA, Inlyr. Visual mock-ups stay controlled by code.', validation: r => r.length(3)}), requiredText('finalCtaHeading', 'Final CTA heading'), paragraph('finalCtaCopy', 'Final CTA copy', true), seoField,
 ], preview: {prepare: () => ({title: 'Homepage'})}}),
 defineType({name: 'service', title: 'Service', type: 'document', fields: [
  requiredText('title', 'Service name'), slugField, defineField({name: 'category', title: 'Service pillar', type: 'string', options: {list: [{title: 'AI & Automation', value: 'ai'}, {title: 'XR & Spatial Computing', value: 'xr'}]}, validation: r => r.required()}), paragraph('shortDescription', 'Short description', true), requiredText('headline', 'Page heading', 'The page H1. Explain the service plainly.'), paragraph('introduction', 'Introduction', true), defineField({name: 'overviewHeading', title: 'Overview question heading', type: 'string'}), paragraph('overviewCopy', 'Overview answer'), contentItems('useCases', 'What we can build'), contentItems('capabilities', 'Platform and technical capabilities'), stringList('technologies', 'Technology line'), refs('featuredProjects', 'Featured work', ['project']), defineField({name: 'faqs', title: 'Buyer questions', type: 'array', of: [defineArrayMember({type: 'faq'})]}),
  defineField({name: 'deliveryHeading', title: 'Team section heading', type: 'string'}), paragraph('deliveryIntroduction', 'Team section introduction'), paragraph('deliveryApproach', 'Delivery approach'), stringList('productionCapabilities', 'Production skills we can assemble', 'Do not imply all disciplines are permanent employees. Intelligence Layer leads delivery.'), paragraph('workIntroduction', 'Featured work introduction'), seoField, defineField({name: 'publishedAt', title: 'Publication date', type: 'datetime'}),
 ], preview: {select: {title: 'title', subtitle: 'category'}}}),
 defineType({name: 'project', title: 'Project / Case study', type: 'document', fields: [
  requiredText('title', 'Project title'), slugField, requiredText('category', 'Category'), requiredText('headline', 'Short headline'), paragraph('shortDescription', 'Project description', true, 'Only describe work Intelligence Layer helped conceive, direct, develop or deliver. Do not invent outcomes or reuse independent studio work.'), bodyField, defineField({name: 'featured', title: 'Feature on homepage by default', type: 'boolean', initialValue: false}), stringList('tags', 'Project tags'), defineField({name: 'coverImage', title: 'Project thumbnail', type: 'editorialImage'}), defineField({name: 'gallery', title: 'Project gallery', type: 'array', of: [defineArrayMember({type: 'editorialImage'})]}), defineField({name: 'video', title: 'Project video', type: 'videoEmbed'}), defineField({name: 'videoPoster', title: 'Video poster', type: 'editorialImage'}), stringList('technologies', 'Technologies'), stringList('platforms', 'Platforms'), refs('services', 'Related services', ['service']), defineField({name: 'projectType', title: 'Project type', type: 'string', options: {list: ['Client engagement','Product','Independent concept']}}),
  defineField({name: 'clientName', title: 'Client name (not public by default)', type: 'string'}), defineField({name: 'showClientName', title: 'Client attribution approved for display', type: 'boolean', initialValue: false, description: 'Names are not yet rendered by the website. A deliberate developer change is required to publish attribution.'}),
  stringList('collaborators', 'Collaborators (not public by default)', 'Only for approved attribution on Intelligence Layer projects. Do not advertise delivery businesses.'), defineField({name: 'showCollaborators', title: 'Collaboration attribution approved for display', type: 'boolean', initialValue: false, description: 'Names are not automatically exposed. A deliberate developer change is required to publish attribution.'}),
  paragraph('attributionNote', 'Public context / affiliation note', false, 'Use for factual project context, such as independent concept status. Do not add unapproved client or collaborator names.'), defineField({name: 'externalUrl', title: 'External project link', type: 'url', validation: r => r.uri({scheme: ['https']})}), defineField({name: 'projectStatus', title: 'Project status', type: 'string', options: {list: ['Concept','Prototype','In development','Released']}}), defineField({name: 'publishedAt', title: 'Publication date', type: 'datetime'}), seoField,
 ], preview: {select: {title: 'title', subtitle: 'category', media: 'coverImage'}}}),
 defineType({name: 'insight', title: 'Insight / Article', type: 'document', fields: [requiredText('title', 'Article title'), slugField, paragraph('excerpt', 'Excerpt', true), defineField({name: 'coverImage', title: 'Cover image', type: 'editorialImage'}), {...bodyField, validation: r => r.required().min(1)}, requiredText('author', 'Author display name'), defineField({name: 'publishedAt', title: 'Publication date', type: 'datetime', validation: r => r.required()}), defineField({name: 'updatedAt', title: 'Updated date', type: 'datetime'}), defineField({name: 'category', title: 'Category', type: 'string'}), refs('relatedServices', 'Related services', ['service']), refs('relatedProjects', 'Related projects', ['project']), seoField], preview: {select: {title: 'title', subtitle: 'author', media: 'coverImage'}}}),
 defineType({name: 'testimonial', title: 'Testimonial (prepared, not displayed)', type: 'document', fields: [paragraph('quote', 'Quote', true), requiredText('name', 'Name'), defineField({name: 'role', title: 'Role', type: 'string'}), defineField({name: 'organisation', title: 'Organisation', type: 'string'}), defineField({name: 'image', title: 'Image', type: 'editorialImage'}), defineField({name: 'approvedForPublication', title: 'Approved for publication', type: 'boolean', initialValue: false, description: 'No testimonials are rendered yet. Future displays must require this approval.'})], preview: {select: {title: 'name', subtitle: 'quote'}}}),
];
